language: julia
os:
  - osx
  - linux
julia:
  - "0.7"
  - "1.0"
  - "nightly"
notifications:
  email: false
script:
  - if [ -a .git/shallow ]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("SIMD")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
